name: Streamlit App Workflow

on:
  push:
    branches:
      - main
env:
  email: ${{ secrets.MDB_EMAIL }}
  pwd: ${{ secrets.MDB_PWD }}
  model: ${{ secrets.MODEL_NAME }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit App
      run: |
        streamlit run app.py
